- service_id: 1
  series_id: NAPEW.ONYX.1
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: mbp-1
  data_source: onyx
  destination:
  - redis1
  extractor: realtime
  description: 1st East-West Naphtha
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 2
  series_id: NAPEW.ONYX.2
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: mbp-1
  data_source: onyx
  destination:
  - redis1
  extractor: realtime
  description: 2nd East-West Naphtha
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 3
  series_id: NAPEW.ONYX.3
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: mbp-1
  data_source: onyx
  destination:
  - redis1
  extractor: realtime
  description: 3rd East-West Naphtha
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 4
  series_id: NAPEW.ONYX.4
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: mbp-1
  data_source: onyx
  destination:
  - redis1
  extractor: realtime
  description: 4th East-West Naphtha
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 5
  series_id: NAPEW.ONYX.5
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: mbp-1
  data_source: onyx
  destination:
  - redis1
  extractor: realtime
  description: 5th East-West Naphtha
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 6
  series_id: NAPEW.ONYX.6
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: mbp-1
  data_source: onyx
  destination:
  - redis1
  extractor: realtime
  description: 6th East-West Naphtha
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 7
  series_id: NAPEW.ONYX.7
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: mbp-1
  data_source: onyx
  destination:
  - redis1
  extractor: realtime
  description: 7th East-West Naphtha
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 8
  series_id: NAPEW.ONYX.8
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: mbp-1
  data_source: onyx
  destination:
  - redis1
  extractor: realtime
  description: 8th East-West Naphtha
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 9
  series_id: NAPEW.ONYX.9
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: mbp-1
  data_source: onyx
  destination:
  - redis1
  extractor: realtime
  description: 9th East-West Naphtha
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 10
  series_id: NAPEW.ONYX.10
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: mbp-1
  data_source: onyx
  destination:
  - redis1
  extractor: realtime
  description: 10th East-West Naphtha
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 11
  series_id: NAPEW.ONYX.11
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: mbp-1
  data_source: onyx
  destination:
  - redis1
  extractor: realtime
  description: 11th East-West Naphtha
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 12
  series_id: NAPEW.ONYX.12
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: mbp-1
  data_source: onyx
  destination:
  - redis1
  extractor: realtime
  description: 12th East-West Naphtha
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 13
  series_id: NAPEW.ONYX.13
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: mbp-1
  data_source: onyx
  destination:
  - redis1
  extractor: realtime
  description: 13th East-West Naphtha
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 14
  series_id: NAPEW.ONYX.14
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: mbp-1
  data_source: onyx
  destination:
  - redis1
  extractor: realtime
  description: 14th East-West Naphtha
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 15
  series_id: NAPEW.ONYX.15
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: mbp-1
  data_source: onyx
  destination:
  - redis1
  extractor: realtime
  description: 15th East-West Naphtha
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 16
  series_id: NAPEW.ONYX.16
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: mbp-1
  data_source: onyx
  destination:
  - redis1
  extractor: realtime
  description: 16th East-West Naphtha
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 17
  series_id: NAPEW.ONYX.17
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: mbp-1
  data_source: onyx
  destination:
  - redis1
  extractor: realtime
  description: 17th East-West Naphtha
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 18
  series_id: NAPEW.ONYX.18
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: mbp-1
  data_source: onyx
  destination:
  - redis1
  extractor: realtime
  description: 18th East-West Naphtha
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 19
  series_id: NAPEW.ONYX.19
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: mbp-1
  data_source: onyx
  destination:
  - redis1
  extractor: realtime
  description: 19th East-West Naphtha
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 20
  series_id: NAPEW.ONYX.20
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: mbp-1
  data_source: onyx
  destination:
  - redis1
  extractor: realtime
  description: 20th East-West Naphtha
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 21
  series_id: NAPEW.ONYX.1
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: ohlcv-1d
  data_source: onyx
  destination:
  - redis1
  extractor: historical
  description: 1st East-West Naphtha
  additional_params:
    redis:
      type: kv
      field: close
  symbol: null
  active: true
- service_id: 22
  series_id: NAPEW.ONYX.2
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: ohlcv-1d
  data_source: onyx
  destination:
  - redis1
  extractor: historical
  description: 2nd East-West Naphtha
  additional_params:
    redis:
      type: kv
      field: close
  symbol: null
  active: true
- service_id: 23
  series_id: NAPEW.ONYX.3
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: ohlcv-1d
  data_source: onyx
  destination:
  - redis1
  extractor: historical
  description: 3rd East-West Naphtha
  additional_params:
    redis:
      type: kv
      field: close
  symbol: null
  active: true
- service_id: 24
  series_id: NAPEW.ONYX.4
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: ohlcv-1d
  data_source: onyx
  destination:
  - redis1
  extractor: historical
  description: 4th East-West Naphtha
  additional_params:
    redis:
      type: kv
      field: close
  symbol: null
  active: true
- service_id: 25
  series_id: NAPEW.ONYX.5
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: ohlcv-1d
  data_source: onyx
  destination:
  - redis1
  extractor: historical
  description: 5th East-West Naphtha
  additional_params:
    redis:
      type: kv
      field: close
  symbol: null
  active: true
- service_id: 26
  series_id: NAPEW.ONYX.6
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: ohlcv-1d
  data_source: onyx
  destination:
  - redis1
  extractor: historical
  description: 6th East-West Naphtha
  additional_params:
    redis:
      type: kv
      field: close
  symbol: null
  active: true
- service_id: 27
  series_id: NAPEW.ONYX.7
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: ohlcv-1d
  data_source: onyx
  destination:
  - redis1
  extractor: historical
  description: 7th East-West Naphtha
  additional_params:
    redis:
      type: kv
      field: close
  symbol: null
  active: true
- service_id: 28
  series_id: NAPEW.ONYX.8
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: ohlcv-1d
  data_source: onyx
  destination:
  - redis1
  extractor: historical
  description: 8th East-West Naphtha
  additional_params:
    redis:
      type: kv
      field: close
  symbol: null
  active: true
- service_id: 29
  series_id: NAPEW.ONYX.9
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: ohlcv-1d
  data_source: onyx
  destination:
  - redis1
  extractor: historical
  description: 9th East-West Naphtha
  additional_params:
    redis:
      type: kv
      field: close
  symbol: null
  active: true
- service_id: 30
  series_id: NAPEW.ONYX.10
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: ohlcv-1d
  data_source: onyx
  destination:
  - redis1
  extractor: historical
  description: 10th East-West Naphtha
  additional_params:
    redis:
      type: kv
      field: close
  symbol: null
  active: true
- service_id: 31
  series_id: NAPEW.ONYX.11
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: ohlcv-1d
  data_source: onyx
  destination:
  - redis1
  extractor: historical
  description: 11th East-West Naphtha
  additional_params:
    redis:
      type: kv
      field: close
  symbol: null
  active: true
- service_id: 32
  series_id: NAPEW.ONYX.12
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: ohlcv-1d
  data_source: onyx
  destination:
  - redis1
  extractor: historical
  description: 12th East-West Naphtha
  additional_params:
    redis:
      type: kv
      field: close
  symbol: null
  active: true
- service_id: 33
  series_id: NAPEW.ONYX.13
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: ohlcv-1d
  data_source: onyx
  destination:
  - redis1
  extractor: historical
  description: 13th East-West Naphtha
  additional_params:
    redis:
      type: kv
      field: close
  symbol: null
  active: true
- service_id: 34
  series_id: NAPEW.ONYX.14
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: ohlcv-1d
  data_source: onyx
  destination:
  - redis1
  extractor: historical
  description: 14th East-West Naphtha
  additional_params:
    redis:
      type: kv
      field: close
  symbol: null
  active: true
- service_id: 35
  series_id: NAPEW.ONYX.15
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: ohlcv-1d
  data_source: onyx
  destination:
  - redis1
  extractor: historical
  description: 15th East-West Naphtha
  additional_params:
    redis:
      type: kv
      field: close
  symbol: null
  active: true
- service_id: 36
  series_id: NAPEW.ONYX.16
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: ohlcv-1d
  data_source: onyx
  destination:
  - redis1
  extractor: historical
  description: 16th East-West Naphtha
  additional_params:
    redis:
      type: kv
      field: close
  symbol: null
  active: true
- service_id: 37
  series_id: NAPEW.ONYX.17
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: ohlcv-1d
  data_source: onyx
  destination:
  - redis1
  extractor: historical
  description: 17th East-West Naphtha
  additional_params:
    redis:
      type: kv
      field: close
  symbol: null
  active: true
- service_id: 38
  series_id: NAPEW.ONYX.18
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: ohlcv-1d
  data_source: onyx
  destination:
  - redis1
  extractor: historical
  description: 18th East-West Naphtha
  additional_params:
    redis:
      type: kv
      field: close
  symbol: null
  active: true
- service_id: 39
  series_id: NAPEW.ONYX.19
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: ohlcv-1d
  data_source: onyx
  destination:
  - redis1
  extractor: historical
  description: 19th East-West Naphtha
  additional_params:
    redis:
      type: kv
      field: close
  symbol: null
  active: true
- service_id: 40
  series_id: NAPEW.ONYX.20
  series_type: fut
  root_id: NAPEW.ONYX
  venue: ONYX
  data_schema: ohlcv-1d
  data_source: onyx
  destination:
  - redis1
  extractor: historical
  description: 20th East-West Naphtha
  additional_params:
    redis:
      type: kv
      field: close
  symbol: null
  active: true
- service_id: 41
  series_id: GC.CME.1
  series_type: fut
  root_id: GC.CME
  venue: CME
  data_schema: mbp-1
  data_source: databento
  destination:
  - redis1
  extractor: realtime
  description: 1st Gold Futures
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 42
  series_id: GC.CME.2
  series_type: fut
  root_id: GC.CME
  venue: CME
  data_schema: mbp-1
  data_source: databento
  destination:
  - redis1
  extractor: realtime
  description: 2nd Gold Futures
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 43
  series_id: GC.CME.3
  series_type: fut
  root_id: GC.CME
  venue: CME
  data_schema: mbp-1
  data_source: databento
  destination:
  - redis1
  extractor: realtime
  description: 3rd Gold Futures
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 44
  series_id: GC.CME.4
  series_type: fut
  root_id: GC.CME
  venue: CME
  data_schema: mbp-1
  data_source: databento
  destination:
  - redis1
  extractor: realtime
  description: 4th Gold Futures
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 45
  series_id: GC.CME.5
  series_type: fut
  root_id: GC.CME
  venue: CME
  data_schema: mbp-1
  data_source: databento
  destination:
  - redis1
  extractor: realtime
  description: 5th Gold Futures
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 46
  series_id: GC.CME.6
  series_type: fut
  root_id: GC.CME
  venue: CME
  data_schema: mbp-1
  data_source: databento
  destination:
  - redis1
  extractor: realtime
  description: 6th Gold Futures
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 47
  series_id: GC.CME.7
  series_type: fut
  root_id: GC.CME
  venue: CME
  data_schema: mbp-1
  data_source: databento
  destination:
  - redis1
  extractor: realtime
  description: 7th Gold Futures
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 48
  series_id: GC.CME.8
  series_type: fut
  root_id: GC.CME
  venue: CME
  data_schema: mbp-1
  data_source: databento
  destination:
  - redis1
  extractor: realtime
  description: 8th Gold Futures
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 49
  series_id: GC.CME.9
  series_type: fut
  root_id: GC.CME
  venue: CME
  data_schema: mbp-1
  data_source: databento
  destination:
  - redis1
  extractor: realtime
  description: 9th Gold Futures
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 50
  series_id: GC.CME.10
  series_type: fut
  root_id: GC.CME
  venue: CME
  data_schema: mbp-1
  data_source: databento
  destination:
  - redis1
  extractor: realtime
  description: 10th Gold Futures
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 51
  series_id: GC.CME.11
  series_type: fut
  root_id: GC.CME
  venue: CME
  data_schema: mbp-1
  data_source: databento
  destination:
  - redis1
  extractor: realtime
  description: 11th Gold Futures
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 52
  series_id: GC.CME.12
  series_type: fut
  root_id: GC.CME
  venue: CME
  data_schema: mbp-1
  data_source: databento
  destination:
  - redis1
  extractor: realtime
  description: 12th Gold Futures
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 53
  series_id: PFATIOCH.SGX
  series_type: index
  root_id: PFATIOCH.SGX
  venue: SGX
  data_schema: ohlcv-1d
  data_source: mkt_db
  destination:
  - database1
  extractor: historical
  description: PLATTS IODEX CFR CHINA 62% Fe $/DMT
  additional_params:
    table_name: sgx.tsi_index
    date_column: TIMESTAMP
  symbol: null
  active: true
- service_id: 54
  series_id: XAGUSD
  series_type: fx
  root_id: XAGUSD
  venue: GLOBAL
  data_schema: mbp-1
  data_source: bbg
  destination:
  - redis1
  extractor: realtime
  description: Silver Spot
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 55
  series_id: XAUUSD
  series_type: fx
  root_id: XAUUSD
  venue: GLOBAL
  data_schema: mbp-1
  data_source: bbg
  destination:
  - redis1
  extractor: realtime
  description: Gold Spot
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 56
  series_id: XPDUSD
  series_type: fx
  root_id: XPDUSD
  venue: GLOBAL
  data_schema: mbp-1
  data_source: bbg
  destination:
  - redis1
  extractor: realtime
  description: Palladium Spot
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 57
  series_id: XPTUSD
  series_type: fx
  root_id: XPTUSD
  venue: GLOBAL
  data_schema: mbp-1
  data_source: bbg
  destination:
  - redis1
  extractor: realtime
  description: Platinum Spot
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 58
  series_id: LMHADS03.LME
  series_type: fwd
  root_id: LMHADS03.LME
  venue: LME
  data_schema: mbp-1
  data_source: bbg
  destination:
  - redis1
  extractor: realtime
  description: LME Aluminum 3M Forward
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 59
  series_id: LMCADS03.LME
  series_type: fwd
  root_id: LMCADS03.LME
  venue: LME
  data_schema: mbp-1
  data_source: bbg
  destination:
  - redis1
  extractor: realtime
  description: LME Copper 3M Forward
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 60
  series_id: LMNIDS03.LME
  series_type: fwd
  root_id: LMNIDS03.LME
  venue: LME
  data_schema: mbp-1
  data_source: bbg
  destination:
  - redis1
  extractor: realtime
  description: LME Nickel 3M Forward
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 61
  series_id: LMPBDS03.LME
  series_type: fwd
  root_id: LMPBDS03.LME
  venue: LME
  data_schema: mbp-1
  data_source: bbg
  destination:
  - redis1
  extractor: realtime
  description: LME Lead 3M Forward
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
- service_id: 62
  series_id: LMZSDS03.LME
  series_type: fwd
  root_id: LMZSDS03.LME
  venue: LME
  data_schema: mbp-1
  data_source: bbg
  destination:
  - redis1
  extractor: realtime
  description: LME Zinc 3M Forward
  additional_params:
    redis:
      type: stream
  symbol: null
  active: true
