- {'root_id': 'CL', 'asset_type': 'fut', 'bbg_root_id': 'CL', 'year_digit': 1, 'suffix': 'Comdty'},
- {'root_id': 'CO', 'asset_type': 'fut', 'bbg_root_id': 'CO', 'year_digit': 1, 'suffix': 'Comdty'},
- {'root_id': 'GC', 'asset_type': 'fut', 'bbg_root_id': 'GC', 'year_digit': 1, 'suffix': 'Comdty'},
- {'root_id': 'HG', 'asset_type': 'fut', 'bbg_root_id': 'HG', 'year_digit': 1, 'suffix': 'Comdty'},
- {'root_id': 'LA', 'asset_type': 'fut', 'bbg_root_id': 'LA', 'year_digit': 2, 'suffix': 'Comdty'},
- {'root_id': 'LL', 'asset_type': 'fut', 'bbg_root_id': 'LL', 'year_digit': 1, 'suffix': 'Comdty'},
- {'root_id': 'LN', 'asset_type': 'fut', 'bbg_root_id': 'LN', 'year_digit': 1, 'suffix': 'Comdty'},
- {'root_id': 'LP', 'asset_type': 'fut', 'bbg_root_id': 'LP', 'year_digit': 2, 'suffix': 'Comdty'},
- {'root_id': 'LX', 'asset_type': 'fut', 'bbg_root_id': 'LX', 'year_digit': 1, 'suffix': 'Comdty'},
- {'root_id': 'NG', 'asset_type': 'fut', 'bbg_root_id': 'NG', 'year_digit': 2, 'suffix': 'Comdty'},
- {'root_id': 'PA', 'asset_type': 'fut', 'bbg_root_id': 'PA', 'year_digit': 1, 'suffix': 'Comdty'},
- {'root_id': 'PL', 'asset_type': 'fut', 'bbg_root_id': 'PL', 'year_digit': 1, 'suffix': 'Comdty'},
- {'root_id': 'QS', 'asset_type': 'fut', 'bbg_root_id': 'QS', 'year_digit': 1, 'suffix': 'Comdty'},
- {'root_id': 'SI', 'asset_type': 'fut', 'bbg_root_id': 'SI', 'year_digit': 1, 'suffix': 'Comdty'},
- {'root_id': 'XB', 'asset_type': 'fut', 'bbg_root_id': 'XB', 'year_digit': 1, 'suffix': 'Comdty'},
- {'root_id': 'LMHADS03', 'asset_type': 'forward', 'bbg_root_id': 'LMHADS03', 'year_digit': 0, 'suffix': 'Comdty' },
- {'root_id': 'LMCADS03', 'asset_type': 'forward', 'bbg_root_id': 'LMCADS03', 'year_digit': 0, 'suffix': 'Comdty' },
- {'root_id': 'LMNIDS03', 'asset_type': 'forward', 'bbg_root_id': 'LMNIDS03', 'year_digit': 0, 'suffix': 'Comdty' },
- {'root_id': 'LMPBDS03', 'asset_type': 'forward', 'bbg_root_id': 'LMPBDS03', 'year_digit': 0, 'suffix': 'Comdty' },
- {'root_id': 'LMZSDS03', 'asset_type': 'forward', 'bbg_root_id': 'LMZSDS03', 'year_digit': 0, 'suffix': 'Comdty' },
- {'root_id': 'XAGUSD', 'asset_type': 'fx', 'bbg_root_id': 'XAGUSD', 'year_digit': 0, 'suffix': 'Curncy' },
- {'root_id': 'XAUSUSD', 'asset_type': 'fx', 'bbg_root_id': 'XAUSUSD', 'year_digit': 0, 'suffix': 'Curncy' },
- {'root_id': 'XPOUSD', 'asset_type': 'fx', 'bbg_root_id': 'XPOUSD', 'year_digit': 0, 'suffix': 'Curncy'},
- {'root_id': 'XPTUSD', 'asset_type': 'fx', 'bbg_root_id': 'XPTUSD', 'year_digit': 0, 'suffix': 'Curncy'}