# Futures Specification

futures_spec:
  energy:
    CME.CL:
      terms: 24
      contract_size: 1000
      description: WTI Futures
      time_zone: America/New_York
      trading_hours:
        open_time_local: "18:00:00"
        close_time_local: "17:00:00"
        trading_days: [ 6,0,1,2,3,4]
      contract_months: [Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec]
      active: true
    CME.QM:
      terms: 12
      contract_size: 500
      description: E-mini WTI Futures
      time_zone: America/New_York
      trading_hours:
        open_time_local: "18:00:00"
        close_time_local: "17:00:00"
        trading_days: [ 6,0,1,2,3,4 ]
      contract_months: [ Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec ]
      active: true
    CME.MCL:
      terms: 12
      contract_size: 100
      description: Micro WTI Futures
      time_zone: America/New_York
      trading_hours:
        open_time_local: "18:00:00"
        close_time_local: "17:00:00"
        trading_days: [ 6,0,1,2,3,4 ]
      contract_months: [ Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec ]
      active: true
    CME.NG:
      terms: 24
      contract_size: 10000
      description: Natural Gas Henry Hub Futures
      time_zone: America/New_York
      trading_hours:
        open_time_local: "18:00:00"
        close_time_local: "17:00:00"
        trading_days: [6,0,1,2,3,4]
      contract_months: [Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec]
      active: true
    CME.QG:
      terms: 12
      contract_size: 2500
      description: E-mini Natural Gas Henry Hub Futures
      time_zone: America/New_York
      trading_hours:
        open_time_local: "18:00:00"
        close_time_local: "17:00:00"
        trading_days: [ 6,0,1,2,3,4 ]
      contract_months: [ Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec ]
      active: true
    CME.MNG:
      terms: 12
      contract_size: 1000
      description: Micro Natural Gas Henry Hub Futures
      time_zone: America/New_York
      trading_hours:
        open_time_local: "18:00:00"
        close_time_local: "17:00:00"
        trading_days: [ 6,0,1,2,3,4 ]
      contract_months: [ Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec ]
      active: true
    CME.RB:
      terms: 12
      contract_size: 42000
      description: RBOB Futures
      time_zone: America/New_York
      trading_hours:
        open_time_local: "18:00:00"
        close_time_local: "17:00:00"
        trading_days: [ 6,0,1,2,3,4 ]
      contract_months: [ Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec ]
      active: true
    ICE.G:
      terms: 24
      contract_size: 100
      description: Low-Sulfur Gasoil Futures
      time_zone: America/New_York
      trading_hours:
        open_time_local: "20:00:00"
        close_time_local: "18:00:00"
        trading_days: [ 6,0,1,2,3,4 ]
      contract_months: [ Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec ]
      active: true
    ICE.B:
      terms: 24
      contract_size: 1000
      description: Brent Futures
      time_zone: America/New_York
      trading_hours:
        open_time_local: "20:00:00"
        close_time_local: "18:00:00"
        trading_days: [ 6,0,1,2,3,4 ]
      contract_months: [ Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec ]
      active: true
    ONYX.NAPEW:
      terms: 20
      contract_size: 1000
      description: East-West Naphtha
      time_zone: America/New_York
      trading_hours:
        open_time_local: "18:00:00"
        close_time_local: "17:00:00"
        trading_days: [ 6,0,1,2,3,4 ]
      contract_months: [ Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec ]
      active: true

  precious_metals:
    CME.GC:
      terms: 12
      contract_size: 100
      description: Gold Futures
      time_zone: America/New_York
      trading_hours:
        open_time_local: "18:00:00"
        close_time_local: "17:00:00"
        trading_days: [ 6,0,1,2,3,4 ]
      contract_months: [ Feb, Apr, Jun, Aug, Oct, Dec ]
      active: true
    CME.QO:
      terms: 6
      contract_size: 50
      description: E-mini Gold Futures
      time_zone: America/New_York
      trading_hours:
        open_time_local: "18:00:00"
        close_time_local: "17:00:00"
        trading_days: [ 6,0,1,2,3,4 ]
      contract_months: [ Feb, Apr, Jun, Aug, Oct, Dec ]
      active: true
    CME.MGC:
      terms: 6
      contract_size: 10
      description: Micro Gold Futures
      time_zone: America/New_York
      trading_hours:
        open_time_local: "18:00:00"
        close_time_local: "17:00:00"
        trading_days: [ 6,0,1,2,3,4 ]
      contract_months: [ Feb, Apr, Jun, Aug, Oct, Dec ]
      active: true
    CME.1OZ:
      terms: 6
      contract_size: 1
      description: 1-Ounce Gold Futures
      time_zone: America/New_York
      trading_hours:
        open_time_local: "18:00:00"
        close_time_local: "17:00:00"
        trading_days: [ 6,0,1,2,3,4 ]
      contract_months: [ Feb, Apr, Jun, Aug, Oct, Dec ]
      active: true
    CME.SI:
      terms: 12
      contract_size: 5000
      description: Silver Futures
      time_zone: America/New_York
      trading_hours:
        open_time_local: "18:00:00"
        close_time_local: "17:00:00"
        trading_days: [ 6,0,1,2,3,4]
      contract_months: [ Jan, Mar, May, Jul, Sep, Dec]
      active: true
    CME.QI:
      terms: 12
      contract_size: 2500
      description: E-mini Silver Futures
      time_zone: America/New_York
      trading_hours:
        open_time_local: "18:00:00"
        close_time_local: "17:00:00"
        trading_days: [ 6,0,1,2,3,4 ]
      contract_months: [ Jan, Mar, May, Jul, Sep, Dec ]
      active: true
    CME.SIL:
      terms: 12
      contract_size: 1000
      description: Micro Silver Futures
      time_zone: America/New_York
      trading_hours:
        open_time_local: "18:00:00"
        close_time_local: "17:00:00"
        trading_days: [ 6,0,1,2,3,4 ]
      contract_months: [ Jan, Mar, May, Jul, Sep, Dec ]
      active: true
    CME.PL:
      terms: 12
      contract_size: 50
      description: Platinum Futures
      time_zone: America/New_York
      trading_hours:
        open_time_local: "18:00:00"
        close_time_local: "17:00:00"
        trading_days: [ 6,0,1,2,3,4 ]
      contract_months: [ Jan, Apr, Jul, Oct ]
      active: true
    CME.PA:
      terms: 12
      contract_size: 100
      description: Palladium Futures
      time_zone: America/New_York
      trading_hours:
        open_time_local: "18:00:00"
        close_time_local: "17:00:00"
        trading_days: [ 6,0,1,2,3,4 ]
      contract_months: [ Mar, Jun, Sep, Dec ]
      active: true
  base_metals:
    CME.HG:
      terms: 12
      contract_size: 25000
      description: Copper Futures
      time_zone: America/New_York
      trading_hours:
        open_time_local: "18:00:00"
        close_time_local: "17:00:00"
        trading_days: [ 6,0,1,2,3,4 ]
      contract_months: [ Mar, May, Jul, Sep, Dec ]
      active: true
    CME.MHG:
      terms: 12
      contract_size: 2500
      description: Micro Copper Futures
      time_zone: America/New_York
      trading_hours:
        open_time_local: "18:00:00"
        close_time_local: "17:00:00"
        trading_days: [ 6,0,1,2,3,4 ]
      contract_months: [ Mar, May, Jul, Sep, Dec ]
      active: true
    LME.AH:
      terms: 12
      contract_size: 25
      description: Aluminum Futures
      time_zone: Europe/London
      trading_hours:
        open_time_local: "20:00:00"
        close_time_local: "19:45:00"
        trading_days: [ 0,1,2,3,4 ]
      contract_months: [ Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec ]
      active: true
    LME.PB:
      terms: 12
      contract_size: 25
      description: Lead Futures
      time_zone: Europe/London
      trading_hours:
        open_time_local: "20:00:00"
        close_time_local: "19:45:00"
        trading_days: [ 0,1,2,3,4 ]
      contract_months: [ Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec ]
      active: true
    LME.NI:
      terms: 12
      contract_size: 6
      description: Nickle Futures
      time_zone: Europe/London
      trading_hours:
        open_time_local: "20:00:00"
        close_time_local: "19:45:00"
        trading_days: [0,1,2,3,4]
      contract_months: [Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec]
      active: true
    LME.CA:
      terms: 12
      contract_size: 25
      description: Copper Futures
      time_zone: Europe/London
      trading_hours:
        open_time_local: "20:00:00"
        close_time_local: "19:45:00"
        trading_days: [0,1,2,3,4]
      contract_months: [Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec]
      active: true
    LME.ZS:
      terms: 12
      contract_size: 25
      description: Zinc Futures
      time_zone: Europe/London
      trading_hours:
        open_time_local: "20:00:00"
        close_time_local: "19:45:00"
        trading_days: [0,1,2,3,4]
      contract_months: [Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec]
      active: true
  interest_rate:
    CME.SR3:
      terms: 12
      contract_size: 2500
      description: Three-Month SOFR Futures
      time_zone: America/New_York
      trading_hours:
        open_time_local: "18:00:00"
        close_time_local: "17:00:00"
        trading_days: [ 6,0,1,2,3,4 ]
      contract_months: [Mar, Jun, Sep, Dec] # and the nearest 6 serial contract months
      active: true
  equities:
    CME.NQ:
      terms: 6
      contract_size: 20
      description: E-mini Nasdaq-100 Futures
      time_zone: America/New_York
      trading_hours:
        open_time_local: "18:00:00"
        close_time_local: "17:00:00"
        trading_days: [ 6,0,1,2,3,4 ]
      contract_months: [Mar, Jun, Sep, Dec]
      active: true
    CME.MNQ:
      terms: 6
      contract_size: 2
      description: Micro E-mini Nasdaq-100 Futures
      time_zone: America/New_York
      trading_hours:
        open_time_local: "18:00:00"
        close_time_local: "17:00:00"
        trading_days: [ 6,0,1,2,3,4 ]
      contract_months: [ Mar, Jun, Sep, Dec ]
      active: true
    CME.ES:
      terms: 6
      contract_size: 50
      description: E-mini S&P 500 Futures
      time_zone: America/New_York
      trading_hours:
        open_time_local: "18:00:00"
        close_time_local: "17:00:00"
        trading_days: [ 6,0,1,2,3,4 ]
      contract_months: [ Mar, Jun, Sep, Dec ]
      active: true
    CME.MES:
      terms: 6
      contract_size: 5
      description: Micro E-mini S&P 500 Futures
      time_zone: America/New_York
      trading_hours:
        open_time_local: "18:00:00"
        close_time_local: "17:00:00"
        trading_days: [ 6,0,1,2,3,4 ]
      contract_months: [ Mar, Jun, Sep, Dec ]
      active: true

exchanges:
  NYMEX:
    name: New York Mercantile Exchange
    time_zone: America/New_York
  CME:
    name: Chicago Mercantile Exchange
    time_zone: America/New_York
  ICE:
    name: Intercontinental Exchange
    time_zone: Europe/London
  LME:
    name: London Metal Exchange
    time_zone: Europe/London

# Contract month codes reference
contract_month_codes:
  Jan: F
  Feb: G
  Mar: H
  Apr: J
  May: K
  Jun: M
  Jul: N
  Aug: Q
  Sep: U
  Oct: V
  Nov: X
  Dec: Z