# Futures Specification Configuration
# Contract months mapping: F=Jan, G=Feb, H=Mar, J=Apr, K=May, M=Jun, N=Jul, Q=Aug, U=Sep, V=Oct, X=Nov, Z=Dec

futures_specifications:
  energy:
    CL:
      root_id: CL
      description: NYMEX WTI Futures
      exchange: NYMEX
      time_zone: America/New_York
      trading_hours:
        open_time_utc: "18:00:00"
        close_time_utc: "17:00:00"
      contract_months: [F, G, H, J, K, M, N, Q, U, V, X, Z]
      contract_months_desc: [Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec]

    CO:
      root_id: CO
      description: ICE Brent Futures
      exchange: ICE
      time_zone: Europe/London
      trading_hours:
        open_time_utc: "01:00:00"
        close_time_utc: "23:00:00"
      contract_months: [F, G, H, J, K, M, N, Q, U, V, X, Z]
      contract_months_desc: [Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec]

    NG:
      root_id: NG
      description: NYMEX Natural Gas Henry Hub Futures
      exchange: NYMEX
      time_zone: America/New_York
      trading_hours:
        open_time_utc: "18:00:00"
        close_time_utc: "17:00:00"
      contract_months: [F, G, H, J, K, M, N, Q, U, V, X, Z]
      contract_months_desc: [Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec]

    XB:
      root_id: XB
      description: NYMEX RBOB Futures
      exchange: NYMEX
      time_zone: America/New_York
      trading_hours:
        open_time_utc: "18:00:00"
        close_time_utc: "17:00:00"
      contract_months: [F, G, H, J, K, M, N, Q, U, V, X, Z]
      contract_months_desc: [Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec]

    QS:
      root_id: QS
      description: ICE Low-Sulfur Gasoil Futures
      exchange: ICE
      time_zone: Europe/London
      trading_hours:
        open_time_utc: "01:00:00"
        close_time_utc: "23:00:00"
      contract_months: [F, G, H, J, K, M, N, Q, U, V, X, Z]
      contract_months_desc: [Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec]

  precious_metals:
    GC:
      root_id: GC
      description: CME Gold Futures
      exchange: CME
      time_zone: America/New_York
      trading_hours:
        open_time_utc: "18:00:00"
        close_time_utc: "17:00:00"
      contract_months: [G, J, M, Q, V, Z]
      contract_months_desc: [Feb, Apr, Jun, Aug, Oct, Dec]

    SI:
      root_id: SI
      description: CME Silver Futures
      exchange: CME
      time_zone: America/New_York
      trading_hours:
        open_time_utc: "18:00:00"
        close_time_utc: "17:00:00"
      contract_months: [H, K, N, U, Z]
      contract_months_desc: [Mar, May, Jul, Sep, Dec]

    PL:
      root_id: PL
      description: NYMEX Platinum Futures
      exchange: NYMEX
      time_zone: America/New_York
      trading_hours:
        open_time_utc: "18:00:00"
        close_time_utc: "17:00:00"
      contract_months: [F, J, N, V]
      contract_months_desc: [Jan, Apr, Jul, Oct]

    PA:
      root_id: PA
      description: NYMEX Palladium Futures
      exchange: NYMEX
      time_zone: America/New_York
      trading_hours:
        open_time_utc: "18:00:00"
        close_time_utc: "17:00:00"
      contract_months: [H, M, U, Z]
      contract_months_desc: [Mar, Jun, Sep, Dec]

  base_metals:
    HG:
      root_id: HG
      description: CME Copper Futures
      exchange: CME
      time_zone: America/New_York
      trading_hours:
        open_time_utc: "18:00:00"
        close_time_utc: "17:00:00"
      contract_months: [H, K, N, U, Z]
      contract_months_desc: [Mar, May, Jul, Sep, Dec]

    LA:
      root_id: LA
      description: LME Aluminum Futures
      exchange: LME
      time_zone: Europe/London
      trading_hours:
        open_time_utc: "20:00:00"
        close_time_utc: "19:45:00"
      contract_months: [F, G, H, J, K, M, N, Q, U, V, X, Z]
      contract_months_desc: [Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec]

    LL:
      root_id: LL
      description: LME Lead Futures
      exchange: LME
      time_zone: Europe/London
      trading_hours:
        open_time_utc: "20:00:00"
        close_time_utc: "19:45:00"
      contract_months: [F, G, H, J, K, M, N, Q, U, V, X, Z]
      contract_months_desc: [Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec]

    LN:
      root_id: LN
      description: LME Nickle Futures
      exchange: LME
      time_zone: Europe/London
      trading_hours:
        open_time_utc: "20:00:00"
        close_time_utc: "19:45:00"
      contract_months: [F, G, H, J, K, M, N, Q, U, V, X, Z]
      contract_months_desc: [Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec]

    LP:
      root_id: LP
      description: LME Copper Futures
      exchange: LME
      time_zone: Europe/London
      trading_hours:
        open_time_utc: "20:00:00"
        close_time_utc: "19:45:00"
      contract_months: [F, G, H, J, K, M, N, Q, U, V, X, Z]
      contract_months_desc: [Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec]

    LZ:
      root_id: LZ
      description: LME Zinc Futures
      exchange: LME
      time_zone: Europe/London
      trading_hours:
        open_time_utc: "20:00:00"
        close_time_utc: "19:45:00"
      contract_months: [F, G, H, J, K, M, N, Q, U, V, X, Z]
      contract_months_desc: [Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec]

# Exchange summary
exchanges:
  NYMEX:
    name: New York Mercantile Exchange
    time_zone: America/New_York
    products: [CL, NG, PA, PL, XB]

  CME:
    name: Chicago Mercantile Exchange
    time_zone: America/New_York
    products: [GC, HG, SI]

  ICE:
    name: Intercontinental Exchange
    time_zone: Europe/London
    products: [CO, QS]

  LME:
    name: London Metal Exchange
    time_zone: Europe/London
    products: [LA, LL, LN, LP, LZ]

# Contract month codes reference
contract_month_codes:
  F: January
  G: February
  H: March
  J: April
  K: May
  M: June
  N: July
  Q: August
  U: September
  V: October
  X: November
  Z: December