# Futures Option Specification

futures_option_spec:
  LME.AH.OPT:
    parent: LME.AH
    terms: 18
    contract_size: 25
    description: Aluminum Futures Option
    time_zone: Europe/London
    trading_hours:
      open_time_local: "20:00:00"
      close_time_local: "19:45:00"
      trading_days: [ 0,1,2,3,4 ]
    contract_months: [ Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec ]
    active: true
  LME.PB.OPT:
    parent: LME.PB
    terms: 18
    contract_size: 25
    description: Lead Futures Option
    time_zone: Europe/London
    trading_hours:
      open_time_local: "20:00:00"
      close_time_local: "19:45:00"
      trading_days: [ 0,1,2,3,4 ]
    contract_months: [ Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec ]
    active: true
  LME.NI.OPT:
    parent: LME.NI
    terms: 18
    contract_size: 25
    description: Nickle Futures Option
    time_zone: Europe/London
    trading_hours:
      open_time_local: "20:00:00"
      close_time_local: "19:45:00"
      trading_days: [ 0,1,2,3,4 ]
    contract_months: [ Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec ]
    active: true
  LME.CA.OPT:
    parent: LME.CA
    terms: 18
    contract_size: 25
    description: Copper Futures Option
    time_zone: Europe/London
    trading_hours:
      open_time_local: "20:00:00"
      close_time_local: "19:45:00"
      trading_days: [ 0,1,2,3,4 ]
    contract_months: [ Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec ]
    active: true
  LME.ZS.OPT:
    parent: LME.ZS
    terms: 18
    contract_size: 25
    description: Zinc Futures Option
    time_zone: Europe/London
    trading_hours:
      open_time_local: "20:00:00"
      close_time_local: "19:45:00"
      trading_days: [ 0,1,2,3,4 ]
    contract_months: [ Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec ]
    active: true


contract_month_codes:
  Jan: F
  Feb: G
  Mar: H
  Apr: J
  May: K
  Jun: M
  Jul: N
  Aug: Q
  Sep: U
  Oct: V
  Nov: X
  Dec: Z