# Forward Specification

forward_spec:
  LMHADS03.LME:
    contract_size: 25
    description: LME Aluminum 3M Forward
    time_zone: Europe/London
    ccy: USD
    trading_hours:
      open_time_local: "01:00:00"
      close_time_local: "19:00:00"
      trading_days: [ 0,1,2,3,4 ]
      active: true
  LMCADS03.LME:
    contract_size: 25
    description: LME Copper 3M Forward
    time_zone: Europe/London
    ccy: USD
    trading_hours:
      open_time_local: "01:00:00"
      close_time_local: "19:00:00"
      trading_days: [ 0,1,2,3,4 ]
      active: true
  LMNIDS03.LME:
    contract_size: 6
    description: LME Nickel 3M Forward
    time_zone: Europe/London
    ccy: USD
    trading_hours:
      open_time_local: "01:00:00"
      close_time_local: "19:00:00"
      trading_days: [ 0,1,2,3,4 ]
      active: true
  LMPBDS03.LME:
    contract_size: 25
    description: LME Lead 3M Forward
    time_zone: Europe/London
    ccy: USD
    trading_hours:
      open_time_local: "01:00:00"
      close_time_local: "19:00:00"
      trading_days: [ 0,1,2,3,4 ]
      active: true
  LMZSDS03.LME:
    contract_size: 25
    description: LME Zinc 3M Forward
    time_zone: Europe/London
    ccy: USD
    trading_hours:
      open_time_local: "01:00:00"
      close_time_local: "19:00:00"
      trading_days: [ 0,1,2,3,4 ]
      active: true
