# Forward Specification

forward_spec:
  LME.LMHADS03:
    root_id: LME.LMHADS03
    contract_size: 25
    description: LME Aluminum 3M Forward
    time_zone: Europe/London
    ccy: USD
    trading_hours:
      open_time_local: ["01:00:00"]
      close_time_local: ["19:00:00"]
      trading_days: [ 0,1,2,3,4 ]
      active: true
  LME.LMCADS03:
    root_id: LME.LMCADS03
    contract_size: 25
    description: LME Copper 3M Forward
    time_zone: Europe/London
    ccy: USD
    trading_hours:
      open_time_local: ["01:00:00"]
      close_time_local: ["19:00:00"]
      trading_days: [ 0,1,2,3,4 ]
      active: true
  LME.LMNIDS03:
    root_id: LME.LMNIDS03
    contract_size: 6
    description: LME Nickel 3M Forward
    time_zone: Europe/London
    ccy: USD
    trading_hours:
      open_time_local: ["01:00:00"]
      close_time_local: ["19:00:00"]
      trading_days: [ 0,1,2,3,4 ]
      active: true
  LME.LMPBDS03:
    root_id: LME.LMPBDS03
    contract_size: 25
    description: LME Lead 3M Forward
    time_zone: Europe/London
    ccy: USD
    trading_hours:
      open_time_local: ["01:00:00"]
      close_time_local: ["19:00:00"]
      trading_days: [ 0,1,2,3,4 ]
      active: true
  LME.LMZSDS03:
    root_id: LME.LMZSDS03
    contract_size: 25
    description: LME Zinc 3M Forward
    time_zone: Europe/London
    ccy: USD
    trading_hours:
      open_time_local: ["01:00:00"]
      close_time_local: ["19:00:00"]
      trading_days: [ 0,1,2,3,4 ]
      active: true
