# Time Series pipelines, for futures, all contract share the same meta

root_ids:
  CME.GC:
    pipelines:
      - extractor: realtime
        source: databento
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
      - extractor: realtime
        source: bbg
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
  CME.CL:
    pipelines:
      - extractor: realtime
        source: bbg
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
      - extractor: realtime
        source: databento
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
  CME.NG:
    pipelines:
      - extractor: realtime
        source: bbg
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
      - extractor: realtime
        source: databento
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
  ICE.B:
    pipelines:
      - extractor: realtime
        source: bbg
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
  ICE.G:
    pipelines:
      - extractor: realtime
        source: bbg
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
  CME.HG:
    pipelines:
      - extractor: realtime
        source: bbg
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
      - extractor: realtime
        source: databento
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
  LME.LA:
    pipelines:
      - extractor: realtime
        source: bbg
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
  LME.LL:
    pipelines:
      - extractor: realtime
        source: bbg
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
  LME.LN:
    pipelines:
      - extractor: realtime
        source: bbg
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
  LME.LP:
    pipelines:
      - extractor: realtime
        source: bbg
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
  LME.LX:
    pipelines:
      - extractor: realtime
        source: bbg
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
  CME.PA:
    pipelines:
      - extractor: realtime
        source: bbg
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
      - extractor: realtime
        source: databento
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
  CME.PL:
    pipelines:
      - extractor: realtime
        source: bbg
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
      - extractor: realtime
        source: databento
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
  CME.QS:
    pipelines:
      - extractor: realtime
        source: bbg
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
      - extractor: realtime
        source: databento
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
  CME.SI:
    pipelines:
      - extractor: realtime
        source: bbg
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
      - extractor: realtime
        source: databento
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
  CME.RB:
    pipelines:
      - extractor: realtime
        source: bbg
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
      - extractor: realtime
        source: databento
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
  ONYX.NAPEW:
    pipelines:
      - extractor: realtime
        source: onyx
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
      - extractor: historical
        source: onyx
        schema: ohlcv-1d
        output: redis1
        params: '{"redis":{"type":"kv","field":"close"}}'
  SGX.PFATIOCH:
    pipelines:
      - extractor: historical
        source: mkt_db
        schema: ohlcv-1d
        output: database1
        params: '{"s_table_name":"sgx.tsi_index", "s_date_column":"TIMESTAMP", "t_table_name": "mktdata.FEF_fixing", "qmarket":"FEF.SGX"}'
  XAGUSD:
    pipelines:
      - extractor: realtime
        source: bbg
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
  XPDUSD:
    pipelines:
      - extractor: realtime
        source: bbg
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
  XAUUSD:
    pipelines:
      - extractor: realtime
        source: bbg
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
  XPTUSD:
    pipelines:
      - extractor: realtime
        source: bbg
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
  LME.LMHADS03:
    pipelines:
      - extractor: realtime
        source: bbg
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
  LME.LMCADS03:
    pipelines:
      - extractor: realtime
        source: bbg
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
  LME.LMNIDS03:
    pipelines:
      - extractor: realtime
        source: bbg
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
  LME.LMPBDS03:
    pipelines:
      - extractor: realtime
        source: bbg
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
  LME.LMZSDS03:
    pipelines:
      - extractor: realtime
        source: bbg
        schema: mbp-1
        output: redis1
        params: '{"redis":{"type":"stream"}}'
  LME.AH:
    pipelines:
      - extractor: historical
        source: bbg
        schema: ohlcv-1d
        output: database1
        params: '{}'
  LME.PB:
    pipelines:
      - extractor: historical
        source: bbg
        schema: ohlcv-1d
        output: database1
        params: '{}'
  LME.AH.OPT:
    pipelines:
      - extractor: historical
        source: bbg
        schema: option-1d
        output: database1
        params: '{"t_table_name": "rawdata.LME_AH_daily_option_price"}'
  LME.PB.OPT:
    pipelines:
      - extractor: historical
        source: bbg
        schema: option-1d
        output: database1
        params: '{"t_table_name": "rawdata.LME_PB_daily_option_price"}'
  LME.NI.OPT:
    pipelines:
      - extractor: historical
        source: bbg
        schema: option-1d
        output: database1
        params: '{"t_table_name": "rawdata.LME_NI_daily_option_price"}'
  LME.CA.OPT:
    pipelines:
      - extractor: historical
        source: bbg
        schema: option-1d
        output: database1
        params: '{"t_table_name": "rawdata.LME_CA_daily_option_price"}'
  LME.ZS.OPT:
    pipelines:
      - extractor: historical
        source: bbg
        schema: option-1d
        output: database1
        params: '{"t_table_name": "rawdata.LME_ZS_daily_option_price"}'